/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package pengingat.pomodoro.lockscreen;


import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import pengingat.PenyimpananData;

/**
 *
 * @author Wolf-PC
 */
public class FrameDesign extends javax.swing.JFrame {
    /**
     * Creates new form FrameDesign
     */
    private BufferedImage master;
    private BufferedImage mask;
    private BufferedImage tinted;
    public int duration;
    AltTabStopper s ;
    PenyimpananData pd;
    Connection koneksii;
    public FrameDesign(int duration, Connection koneksi) {
        initComponents();
        this.koneksii = koneksi;
        pd = new PenyimpananData(koneksii);
        this.duration = duration;
        this.s = new AltTabStopper(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //setLocationRelativeTo(null); // biar center
        setBackgroundImage(pd.getbg());
    }
    
    // fungsi untuk ganti background biar mudah
    public void setBackgroundImage(String path) {
        // Ambil Gambar dari Path
        ImageIcon ic = new ImageIcon(path);
        // 1366 width 768 height , Image.SCALE_SMOOTh entahlah :v
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        Image image = ic.getImage().getScaledInstance((int) width, (int) height, Image.SCALE_SMOOTH);
        
        // Ganti BG ;)
        this.setContentPane(new BackgroundPanel(image));
    }
    
    // extends dari Panel yg di buat
    public class BackgroundPanel extends PanelDesign {
        private Image image;
        Thread t, st;
        public class MyThread implements Runnable  {
            public void run(){
                int timet  = duration * 60;
                long delay = timet * 1000;
                do {
                    int minutes = timet / 60;
                    int seconds = timet % 60;
                    String sMinute = minutes + "";
                String sSeconds = seconds + "";
                if (sMinute.length() == 1){
                    jLabel1.setText("0"+minutes+":"+seconds + " Remaining");
                    if (sSeconds.length() == 1){
                       jLabel1.setText("0"+minutes+":0"+seconds + " Remaining"); 
                    }
                }
                else if (sSeconds.length() == 1){
                    jLabel1.setText(minutes+":0"+seconds  + " Remaining");
                    if (sMinute.length() == 1){
                       jLabel1.setText("0"+minutes+":0"+seconds + " Remaining"); 
                    }
                }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                    timet = timet - 1;
                    delay = delay - 1000;
                    
                }
                while (delay != 0);
                t.stop();
                st.stop();
                dispose();
            }
        }
        public class MySecThread implements Runnable  {
            public void run(){
                s.run();
            }
        }
        public BackgroundPanel(Image image) {
            this.image = image;
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel3MouseClicked(evt);
                }
            });
            t = new Thread(new MyThread());
            st = new Thread(new MySecThread());
            st.start();
            t.start();
        }
        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
            // TODO add your handling code here:
            t.stop();
            st.stop();
            dispose();
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
            g.drawImage(image, 0, 0, this);
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
